service: poc-apollo-lambda
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  stage: dev
plugins:
  - serverless-offline
functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
